name: Publish Chart

on:
  push:
   branches: test

   # tags:
    #  - '*'

jobs:
  release:
      name: "Test and Run"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@main
        - name: Run chart version bump
          uses: ./
          with:
            mode: 'publish'
            chartYaml: './chart.yml'
          env:
            GITHUB_TOKEN: "${{ secrets.githubToken }}"
            # HELM_REPO_PASSWORD: "${{ secrets.HELM_REPO_PASSWORD }}"
